using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class NodeModel
{
    [RealtimeProperty(1, true, true)]
    private string _name;
    [RealtimeProperty(2, true, true)]
    private Vector3 _connectionPosA;
    [RealtimeProperty(3, true, true)]
    private Vector3 _connectionPosB;
}
/* ----- Begin Normal Autogenerated Code ----- */
public partial class NodeModel : IModel {
    // Properties
    public string name {
        get { return _cache.LookForValueInCache(_name, entry => entry.nameSet, entry => entry.name); }
        set { if (value == name) return; _cache.UpdateLocalCache(entry => { entry.nameSet = true; entry.name = value; return entry; }); FireNameDidChange(value); }
    }
    public UnityEngine.Vector3 connectionPosA {
        get { return _cache.LookForValueInCache(_connectionPosA, entry => entry.connectionPosASet, entry => entry.connectionPosA); }
        set { if (value == connectionPosA) return; _cache.UpdateLocalCache(entry => { entry.connectionPosASet = true; entry.connectionPosA = value; return entry; }); FireConnectionPosADidChange(value); }
    }
    public UnityEngine.Vector3 connectionPosB {
        get { return _cache.LookForValueInCache(_connectionPosB, entry => entry.connectionPosBSet, entry => entry.connectionPosB); }
        set { if (value == connectionPosB) return; _cache.UpdateLocalCache(entry => { entry.connectionPosBSet = true; entry.connectionPosB = value; return entry; }); FireConnectionPosBDidChange(value); }
    }
    
    // Events
    public delegate void NameDidChange(NodeModel model, string value);
    public event         NameDidChange nameDidChange;
    public delegate void ConnectionPosADidChange(NodeModel model, UnityEngine.Vector3 value);
    public event         ConnectionPosADidChange connectionPosADidChange;
    public delegate void ConnectionPosBDidChange(NodeModel model, UnityEngine.Vector3 value);
    public event         ConnectionPosBDidChange connectionPosBDidChange;
    
    // Delta updates
    private struct LocalCacheEntry {
        public bool                nameSet;
        public string              name;
        public bool                connectionPosASet;
        public UnityEngine.Vector3 connectionPosA;
        public bool                connectionPosBSet;
        public UnityEngine.Vector3 connectionPosB;
    }
    
    private LocalChangeCache<LocalCacheEntry> _cache;
    
    public NodeModel() {
        _cache = new LocalChangeCache<LocalCacheEntry>();
    }
    
    // Events
    public void FireNameDidChange(string value) {
        try {
            if (nameDidChange != null)
                nameDidChange(this, value);
        } catch (System.Exception exception) {
            Debug.LogException(exception);
        }
    }
    public void FireConnectionPosADidChange(UnityEngine.Vector3 value) {
        try {
            if (connectionPosADidChange != null)
                connectionPosADidChange(this, value);
        } catch (System.Exception exception) {
            Debug.LogException(exception);
        }
    }
    public void FireConnectionPosBDidChange(UnityEngine.Vector3 value) {
        try {
            if (connectionPosBDidChange != null)
                connectionPosBDidChange(this, value);
        } catch (System.Exception exception) {
            Debug.LogException(exception);
        }
    }
    
    // Serialization
    enum PropertyID {
        Name = 1,
        ConnectionPosA = 2,
        ConnectionPosB = 3,
    }
    
    public int WriteLength(StreamContext context) {
        int length = 0;
        
        if (context.fullModel) {
            // Mark unreliable properties as clean and flatten the in-flight cache.
            // TODO: Move this out of WriteLength() once we have a prepareToWrite method.
            _name = name;
            _connectionPosA = connectionPosA;
            _connectionPosB = connectionPosB;
            _cache.Clear();
            
            // Write all properties
            length += WriteStream.WriteStringLength((uint)PropertyID.Name, _name);
            length += WriteStream.WriteBytesLength((uint)PropertyID.ConnectionPosA, WriteStream.Vector3ToBytesLength());
            length += WriteStream.WriteBytesLength((uint)PropertyID.ConnectionPosB, WriteStream.Vector3ToBytesLength());
        } else {
            // Reliable properties
            if (context.reliableChannel) {
                LocalCacheEntry entry = _cache.localCache;
                if (entry.nameSet)
                    length += WriteStream.WriteStringLength((uint)PropertyID.Name, entry.name);
                if (entry.connectionPosASet)
                    length += WriteStream.WriteBytesLength((uint)PropertyID.ConnectionPosA, WriteStream.Vector3ToBytesLength());
                if (entry.connectionPosBSet)
                    length += WriteStream.WriteBytesLength((uint)PropertyID.ConnectionPosB, WriteStream.Vector3ToBytesLength());
            }
        }
        
        return length;
    }
    
    public void Write(WriteStream stream, StreamContext context) {
        if (context.fullModel) {
            // Write all properties
            stream.WriteString((uint)PropertyID.Name, _name);
            stream.WriteBytes((uint)PropertyID.ConnectionPosA, WriteStream.Vector3ToBytes(_connectionPosA));
            stream.WriteBytes((uint)PropertyID.ConnectionPosB, WriteStream.Vector3ToBytes(_connectionPosB));
        } else {
            // Reliable properties
            if (context.reliableChannel) {
                LocalCacheEntry entry = _cache.localCache;
                if (entry.nameSet || entry.connectionPosASet || entry.connectionPosBSet)
                    _cache.PushLocalCacheToInflight(context.updateID);
                
                if (entry.nameSet)
                    stream.WriteString((uint)PropertyID.Name, entry.name);
                if (entry.connectionPosASet)
                    stream.WriteBytes((uint)PropertyID.ConnectionPosA, WriteStream.Vector3ToBytes(entry.connectionPosA));
                if (entry.connectionPosBSet)
                    stream.WriteBytes((uint)PropertyID.ConnectionPosB, WriteStream.Vector3ToBytes(entry.connectionPosB));
            }
        }
    }
    
    public void Read(ReadStream stream, StreamContext context) {
        bool nameExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.nameSet);
        bool connectionPosAExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.connectionPosASet);
        bool connectionPosBExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.connectionPosBSet);
        
        // Remove from in-flight
        if (context.deltaUpdatesOnly && context.reliableChannel)
            _cache.RemoveUpdateFromInflight(context.updateID);
        
        // Loop through each property and deserialize
        uint propertyID;
        while (stream.ReadNextPropertyID(out propertyID)) {
            switch (propertyID) {
                case (uint)PropertyID.Name: {
                    string previousValue = _name;
                    
                    _name = stream.ReadString();
                    
                    if (!nameExistsInChangeCache && _name != previousValue)
                        FireNameDidChange(_name);
                    break;
                }
                case (uint)PropertyID.ConnectionPosA: {
                    UnityEngine.Vector3 previousValue = _connectionPosA;
                    
                    _connectionPosA = ReadStream.Vector3FromBytes(stream.ReadBytes());
                    
                    if (!connectionPosAExistsInChangeCache && _connectionPosA != previousValue)
                        FireConnectionPosADidChange(_connectionPosA);
                    break;
                }
                case (uint)PropertyID.ConnectionPosB: {
                    UnityEngine.Vector3 previousValue = _connectionPosB;
                    
                    _connectionPosB = ReadStream.Vector3FromBytes(stream.ReadBytes());
                    
                    if (!connectionPosBExistsInChangeCache && _connectionPosB != previousValue)
                        FireConnectionPosBDidChange(_connectionPosB);
                    break;
                }
                default:
                    stream.SkipProperty();
                    break;
            }
        }
    }
}
/* ----- End Normal Autogenerated Code ----- */
